### ISSUE TITLE
Error: category / does not exist

### ISSUE THREAD

**Issue by vimal-hoh** [christkv/ecommerce#1]
/home/vimal/vimal/ecommerce/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

Error: category / does not exist
    at /home/vimal/vimal/ecommerce/models/category.js:163:39
    at handleCallback (/home/vimal/vimal/ecommerce/node_modules/mongodb/lib/utils.js:96:12)
    at /home/vimal/vimal/ecommerce/node_modules/mongodb/lib/collection.js:1335:5
    at handleCallback (/home/vimal/vimal/ecommerce/node_modules/mongodb/lib/utils.js:96:12)
    at /home/vimal/vimal/ecommerce/node_modules/mongodb/lib/cursor.js:665:5
    at handleCallback (/home/vimal/vimal/ecommerce/node_modules/mongodb-core/lib/cursor.js:244:5)
    at setCursorNotified (/home/vimal/vimal/ecommerce/node_modules/mongodb-core/lib/cursor.js:563:3)
    at /home/vimal/vimal/ecommerce/node_modules/mongodb-core/lib/cursor.js:673:16
    at queryCallback (/home/vimal/vimal/ecommerce/node_modules/mongodb-core/lib/cursor.js:301:18)
    at Callbacks.emit (/home/vimal/vimal/ecommerce/node_modules/mongodb-core/lib/topologies/server.js:95:3)

**Comment by jcbarton** [comment]
Any ideas? Not sure how to add the root category to an initial install.

**Comment by jcbarton** [comment]
Thought I'd leave a note here, in case anyone else hits this:

node tools/pre_load.js

**Comment by r1mar** [comment]
If no categories are there, the program should also not display this. It should not abort with an error. Do you agree?
